version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    # env_file:
    #     - ./.env
    environment:
      - DB_HOST=postgres
      - DATABASE_PORT=5432
      - DB_PASSWORD=pass
      - DB_NAME=fastapi
      - DB_USER=postgres
      - SECRET_KEY=9d90e04c64822436b820a67200827e76ffaa6cf88d0152d252e15e7b93c78732
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXP_MINUTES=30
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: