version: "3"
services:
  api:
    image: ayoubl96/fastapi-learn
    ports:
      - 80:8000
    environment:
      - DB_HOST=${DB_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXP_MINUTES=${ACCESS_TOKEN_EXP_MINUTES}

    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: