"""phone

Revision ID: 08c6d0b6744f
Revises: 08127f14d69a
Create Date: 2024-07-06 03:11:26.687670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c6d0b6744f'
down_revision: Union[str, None] = '08127f14d69a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('phone_number', sa.String(), nullable=True))
    op.alter_column('posts', 'published',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'published',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('Users', 'phone_number')
    # ### end Alembic commands ###
